default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homka_development

test:
  <<: *default
  database: homka_test

production:
  <<: *default
  database: homka_production
  username: chakaboom
  password: <%= ENV['HOMKA_DATABASE_PASSWORD'] %>
